import { useState } from "react";
import { useQuery } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { AllCategoriesQuery } from "../graphql/queries";
import apolloClient from "../lib/apollo";
import styles from "../styles/Home.module.css";
import Search from "../components/hero/search";
import Tab from "../components/hero/Tab";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  const [selectedTab, setSelectedTab] = useState(0);

  const { loading, error, data } = useQuery(AllCategoriesQuery);

  const router = useRouter();

  const handleClick = (id: string) => {
    console.log("clicked");

    router.push({
      pathname: "/products",
      query: { id },
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Shopply</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ marginTop: "100px" }}>
        <Search onSearch={() => {}} />
        <Tab setSelectedTabIndex={setSelectedTab} />
        <Layout selectedTab={selectedTab} />
      </div>
      {/* <div>
        {data.categories.map((category: any) => {
          return (
            <div>
              <h3>{category.name}</h3>
              <p>
                {category.subCategories.map((subCategory: any) => {
                  return <p>{subCategory.name}</p>;
                })}
              </p>
              <button onClick={() => handleClick(category.categoryId)}>
                products
              </button>
            </div>
          );
        })}
      </div> */}
    </div>
  );
};

export default Home;
